=== igstan/bnr-webhooks/java/dropwizard-asavu/src/main/resources/nbrfxrates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.bnr.ro/xsd" xmlns:x="http://www.bnr.ro/xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bnr.ro/xsd" elementFormDefault="qualified"
	attributeFormDefault="qualified">
	<!-- Local types -->
	<xsd:complexType name="LT_Header">
		<xsd:sequence>
			<xsd:element name="Publisher">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[\S]{1}.{0,99}" />
						<xsd:minLength value="1" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="PublishingDate" type="xsd:date" />
			<xsd:element name="MessageType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[A-Z]{2}" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="LT_RateValue">
		<xsd:restriction base="xsd:decimal">
			<xsd:minExclusive value="0" />
			<xsd:pattern value="\d+.\d{4}" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="LT_Cube">
		<xsd:sequence>
			<xsd:element name="Rate" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="LT_RateValue">
							<xsd:attribute name="currency" use="required" form="unqualified">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[A-Z]{3}" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:attribute>
							<xsd:attribute name="multiplier" use="optional" form="unqualified">
								<xsd:simpleType>
									<xsd:restriction base="xsd:integer">
										<xsd:minInclusive value="1" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:attribute>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="date" use="required" form="unqualified" type="xsd:date" />
	</xsd:complexType>
	<!-- Message description -->
	<xsd:element name="DataSet">
		<xsd:annotation>
			<xsd:documentation>nbrfxrates.xsd</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Header" type="LT_Header" />
				<xsd:element name="Body">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Subject">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[\S]{1}.{0,99}" />
										<xsd:minLength value="1" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Description" minOccurs="0">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[\S]{1}.{0,499}" />
										<xsd:minLength value="1" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="OrigCurrency">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[A-Z]{3}" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Cube" type="LT_Cube" maxOccurs="unbounded" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="CubeDateUnique">
			<xsd:selector xpath="./x:Body/x:Cube" />
			<xsd:field xpath="@date" />
		</xsd:unique>
	</xsd:element>
</xsd:schema>

=== igstan/bnr-webhooks/asavu/src/test/resources/nbrfxrates.xml
<?xml version="1.0" encoding="utf-8"?>
<DataSet xmlns="http://www.bnr.ro/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bnr.ro/xsd nbrfxrates.xsd">
	<Header>
		<Publisher>National Bank of Romania</Publisher>
		<PublishingDate>2012-08-21</PublishingDate>
		<MessageType>DR</MessageType>
	</Header>
	<Body>
		<Subject>Reference rates</Subject>
		<OrigCurrency>RON</OrigCurrency>
		<Cube date="2012-08-21">
			<Rate currency="AED">0.9870</Rate>
			<Rate currency="AUD">3.8083</Rate>
			<Rate currency="BGN">2.3002</Rate>
			<Rate currency="BRL">1.7973</Rate>
			<Rate currency="CAD">3.6781</Rate>
			<Rate currency="CHF">3.7469</Rate>
			<Rate currency="CNY">0.5704</Rate>
			<Rate currency="CZK">0.1815</Rate>
			<Rate currency="DKK">0.6041</Rate>
			<Rate currency="EGP">0.5962</Rate>
			<Rate currency="EUR">4.4987</Rate>
			<Rate currency="GBP">5.7123</Rate>
			<Rate currency="HUF" multiplier="100">1.6320</Rate>
			<Rate currency="INR">0.0653</Rate>
			<Rate currency="JPY" multiplier="100">4.5656</Rate>
			<Rate currency="KRW" multiplier="100">0.3206</Rate>
			<Rate currency="MDL">0.2931</Rate>
			<Rate currency="MXN">0.2772</Rate>
			<Rate currency="NOK">0.6144</Rate>
			<Rate currency="NZD">2.9505</Rate>
			<Rate currency="PLN">1.1068</Rate>
			<Rate currency="RSD">0.0381</Rate>
			<Rate currency="RUB">0.1138</Rate>
			<Rate currency="SEK">0.5453</Rate>
			<Rate currency="TRY">2.0165</Rate>
			<Rate currency="UAH">0.4476</Rate>
			<Rate currency="USD">3.6255</Rate>
			<Rate currency="XAU">189.3204</Rate>
			<Rate currency="XDR">5.4823</Rate>
			<Rate currency="ZAR">0.4389</Rate>
		</Cube>
	</Body>
</DataSet>
